### ISSUE TITLE
Add this repo as a resource

### ISSUE THREAD

**Issue by josephmisiti** [rhiever/Data-Analysis-and-Machine-Learning-Projects#11]
https://github.com/josephmisiti/awesome-machine-learning

disclaimer - it is my repo!

**Comment by rhiever** [comment]
Cool - mind adding my blog (randalolson.com/blog/) to your blog list and perhaps this notebook somewhere in your ML list?

**Comment by josephmisiti** [comment]
sure thing

**Comment by rhiever** [comment]
Cheers! :+1:
