### ISSUE TITLE
Some stations do not report average daily temp

### ISSUE THREAD

**Issue by dogunter** [rhiever/Data-Analysis-and-Machine-Learning-Projects#20]
KSAF in Santa Fe, New Mexico does not record an average daily temperature, only the mean. In order for wunderground_parser.py to work in this case, all of the index values need to be shifted down by one after reading weather_data[0].

**Comment by rhiever** [comment]
That's unfortunate. I wonder if there's an easy way to detect if a station doesn't report the average daily temp and perform this shifting when necessary.
