### ISSUE TITLE
KeyError while using seaborn plotting

### ISSUE THREAD

**Issue by mgudipati** [rhiever/Data-Analysis-and-Machine-Learning-Projects#22]
Hi. I am getting KeyError 'class' while attempting to plot iris data.

sb.pairplot(iris_data.dropna(), hue='class')

gives the following stack trace, please advise.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-25-8994735eaa32> in <module>()
----> 1 sb.pairplot(iris_data.dropna(), hue='class')

/Users/mgudipati/anaconda/lib/python2.7/site-packages/seaborn/linearmodels.py in pairplot(data, hue, hue_order, palette, vars, x_vars, y_vars, kind, diag_kind, markers, size, aspect, dropna, plot_kws, diag_kws, grid_kws)
   1583                     hue_order=hue_order, palette=palette,
   1584                     diag_sharey=diag_sharey,
-> 1585                     size=size, aspect=aspect, dropna=dropna, **grid_kws)
   1586 
   1587     # Add the markers here as PairGrid has figured out how many levels of the

/Users/mgudipati/anaconda/lib/python2.7/site-packages/seaborn/axisgrid.py in __init__(self, data, hue, hue_order, palette, hue_kws, vars, x_vars, y_vars, diag_sharey, size, aspect, despine, dropna)
   1221                                       index=data.index)
   1222         else:
-> 1223             hue_names = utils.categorical_order(data[hue], hue_order)
   1224             if dropna:
   1225                 # Filter NA from the list of unique hue names

/Users/mgudipati/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in __getitem__(self, key)
   1990             return self._getitem_multilevel(key)
   1991         else:
-> 1992             return self._getitem_column(key)
   1993 
   1994     def _getitem_column(self, key):

/Users/mgudipati/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _getitem_column(self, key)
   1997         # get column
   1998         if self.columns.is_unique:
-> 1999             return self._get_item_cache(key)
   2000 
   2001         # duplicate columns & possible reduce dimensionality

/Users/mgudipati/anaconda/lib/python2.7/site-packages/pandas/core/generic.pyc in _get_item_cache(self, item)
   1343         res = cache.get(item)
   1344         if res is None:
-> 1345             values = self._data.get(item)
   1346             res = self._box_item_values(item, values)
   1347             cache[item] = res

/Users/mgudipati/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in get(self, item, fastpath)
   3223 
   3224             if not isnull(item):
-> 3225                 loc = self.items.get_loc(item)
   3226             else:
   3227                 indexer = np.arange(len(self.items))[isnull(self.items)]

/Users/mgudipati/anaconda/lib/python2.7/site-packages/pandas/indexes/base.pyc in get_loc(self, key, method, tolerance)
   1876                 return self._engine.get_loc(key)
   1877             except KeyError:
-> 1878                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   1879 
   1880         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4027)()

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3891)()

pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12408)()

pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12359)()

KeyError: 'class'

**Comment by mgudipati** [comment]
It is fixed when I changed the header to be 'species' instead of 'class'. May be 'class' is a keyword?

**Comment by rhiever** [comment]
Are you using different copies of the iris data sets? I have local copies in the notebook that use `class` as the class label column.

**Comment by mfarooq28** [comment]
Your data file does not contains column labels. Use firs row is as column label. Like:

sepal_length_cm | sepal_width_cm | petal_length_cm | petal_width_cm | class|
