### ISSUE TITLE
follower factory's alpha value calculation doesn't work for small accounts

### ISSUE THREAD

**Issue by haraldschilly** [rhiever/Data-Analysis-and-Machine-Learning-Projects#31]
That `alpha = ...` for the plot assumes a large number of followers. Otherwise, the alpha value is out of bounds!

e.g. I think this is an easy fix, although maybe there are better ideas out there for normalizing the transparency w.r.t. the total number of points to plot.

```
alpha=0.1 * min(9, 80000. / len(days_since_2006)))
```

**Comment by srugano** [comment]
Had the same issue for a small account (~800), but tried @haraldschilly solution and it works.

**Comment by rhiever** [comment]
@haraldschilly, can you please submit a PR with this fix? Thank you for bringing it to my attention.

**Comment by aaaadriaaaan** [comment]
Thank you very much @haraldschilly, this worked for me!

**Comment by haraldschilly** [comment]
@aaaadriaaaan oh, your comment reminded me of sending a patch. well, better late than never …
