### ISSUE TITLE
Ball Outcome

### ISSUE THREAD

**Issue by britis22** [rhiever/Data-Analysis-and-Machine-Learning-Projects#35]
Cricinfo want to create a simple cricket simulator to test their scorecard and so have come to you for help.
After a ball is bowled, there are eight possible outcomes. Below we list the eight outcomes and each outcome’s
e"ect on the score:
• 0 runs: add 1 to the ball count
• 1 run: add 1 to the ball count, add 1 to the run count
• 2 runs: add 1 to the ball count, add 2 to the run count
• 4 runs: add 1 to the ball count, add 4 to the run count, add 1 to the 4s count
• 6 runs: add 1 to the ball count, add 6 to the run count, add 1 to the 6s count
• Wide: add 1 to the extras count
• No ball: add 1 to the extras count
• Out: add 1 to the ball count, mark batsman as out
Cricinfo store a batsman’s record using the variable:
state = list(balls = 0, runs = 0, fours = 0, sixes = 0, extras = 0, out = FALSE)
Write the function oneBall that takes the input state and one outcome and returns the updated state based
on the eight outcomes above

**Comment by britis22** [comment]
Please help me with the above question

**Comment by sumit-03** [comment]
i want to do this . 
if  i am right function takes inputs as 1->input state(list)  2->one of possible outcomes.
is it so?

**Comment by britis22** [comment]
Thats right ..X->function(state,outcome)
{
.......
.......
}

**Comment by sumit-03** [comment]
I have done it. please see if that is fine

**Comment by rhiever** [comment]
I see the connection of this issue to #36 now. I suggest creating a separate repository for this project. This is not the place to develop these kinds of projects.
