### ISSUE TITLE
Add BSD or MIT license for code

### ISSUE THREAD

**Issue by ahmadia** [rhiever/Data-Analysis-and-Machine-Learning-Projects#5]
Software Carpentry does this in [their license](http://software-carpentry.org/license.html).  CC [recommends](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) it.

**Comment by rhiever** [comment]
Done.

**Comment by ahmadia** [comment]
:+1:
